name: 'Kube Tools'
description: 'Install kubectl, kustomize, and helm.  To use the tools, please add "gh-" prefix, such as "gh-yq".'
author: 'Joe Huang <jhuang@nowcom.com>'
inputs:
  kubectl:
    description: 'Kubectl version'
    # default: '1.29.0'
  krew:
    description: 'Krew version'
    # default: '0.4.4'
  kustomize:
    description: 'Kustomize version'
    # default: '5.3.0'
  helm:
    description: 'Helm version'
    # default: '3.14.2'
  conftest:
    description: 'Conftest version'
    # default: '0.39.0'
  kubeval:
    description: 'Kubeval version'
    # default: '0.16.1'
  gh:
    description: 'GitHub CLI version'
    # default: '2.45.0'
  yq:
    description: 'Yq version'
    # default: '4.42.1'
  argocd:
    descriptip: 'ArgoCD verion'
    # default: '2.10.4'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: 'node20'
  main: 'dist/index.js'